[package]
edition = "2018"
name = "device"
version = "0.1.0"

[dependencies]
cube_model = { path="../cube_model", features = ["without_std"]}

[build-dependencies]
cbindgen = "0.20.0"

[lib]
crate-type = ["staticlib"]
