name: Code Coverage (nightly rust tools, grcov -> codecov.io)
on: [push]
jobs:
  TestCoverage:
    runs-on: ubuntu-latest
    steps:
      - name: install deps from apt
        run: sudo apt-get install libasound2-dev libudev-dev
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
      - uses: actions-rs/cargo@v1
        with:
          command: test
          args: --workspace --exclude device
        env:
          CARGO_INCREMENTAL: '0'
          RUSTFLAGS: '-Zprofile -Ccodegen-units=1 -Cinline-threshold=0 -Clink-dead-code -Coverflow-checks=off -Cpanic=abort -Zpanic_abort_tests'
          RUSTDOCFLAGS: '-Zprofile -Ccodegen-units=1 -Cinline-threshold=0 -Clink-dead-code -Coverflow-checks=off -Cpanic=abort -Zpanic_abort_tests'
      - name: rust-grcov
        id: coverage
        uses: actions-rs/grcov@v0.1.5
      - uses: codecov/codecov-action@v2
        with:
          files: ${{ steps.coverage.outputs.report }}
