name: GitHub Actions Demo
on: [push]
jobs:
  Tests:
    runs-on: ubuntu-latest
    steps:
      - name: install deps from apt
        run: sudo apt-get install libasound2-dev libudev-dev
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: actions-rs/cargo@v1
        with:
          command: test
          args: --workspace --exclude device
